### ISSUE TITLE
Missing build dependence: bc

### ISSUE THREAD

**Issue by leleobhz** [ptudor/centos6-openssl#14]
In a clean-room Centos 6.6, build with mock gives:

```
test BN_mod_sqrt
.....
.....
.....
.....
.....
.....
.....
.....
....++++++++++++
.....
.++++++++++++
.....
................++++++++++++
.....
.++++++++++++
.....
........++++++++++++
.....
.++++++++++++
.....
....++++++++++++
.....
.++++++++++++
.....
running bc
./bctest: line 35: bc: command not found
bc does not work properly ('SunOStest' failed).  Looking for another bc ...
No working bc found.  Consider installing GNU bc.
```

**Comment by neverping** [comment]
I just built without mock, using a vagrant box 

test BN_mod_sqrt
.....
.....
.....
.....
.....
.....
.....
.....
....++++++++++++
.....
...++++++++++++
.....
......++++++++++++
.....
..........................++++++++++++
.....
........++++++++++++
.....
...................++++++++++++
.....
.....++++++++++++
.....
.......++++++++++++
.....
running bc

verify BN_add....................................................................................................
verify BN_sub......................................................................................................................................................

It's a bit strange this error showing you don't have "bc", since i think it's the most default package on a Linux box.

[vagrant@localhost centos6-openssl]$ bc -v
bc 1.06.95
Copyright 1991-1994, 1997, 1998, 2000, 2004, 2006 Free Software Foundation, Inc.
[vagrant@localhost centos6-openssl]$ cat /etc/redhat-release 
CentOS release 6.6 (Final)

Try "bc -v" on your system.

**Comment by ptudor** [comment]
# which bc 
/usr/bin/bc
# rpm -qf /usr/bin/bc
bc-1.06.95-1.el6.x86_64
