### ISSUE TITLE
F21: ../libssl.so: undefined reference to `__secure_getenv'

### ISSUE THREAD

**Issue by az-z** [ptudor/centos6-openssl#15]
@ptudor 
 i run F21 and used "mock" in attempt to compile the "J" and "K" versions.
Neither worked. Since your README states that this package is for "J" version then all below is about my attempt to compile "J" version.

1. i followed you directions from README in order to compile the rpm.
2. There are 2 "spec" files once in SOURCES - it is referring to "i" version of the openssl and another is in the "root" of the git. This one refers to the "j" version.
 That's a bit confusing to be honest.
3.after rpmbiold -bs and mock on srpm, i get this :

`rm -f openssl
shlib_target=; if [ -n "libcrypto.so.10 libssl.so.10" ]; then \
	shlib_target="linux-shared"; \
elif [ -n "" ]; then \
  FIPSLD_CC="gcc"; CC=/usr/local/ssl/fips-2.0/bin/fipsld; export CC FIPSLD_CC; \
fi; \
LIBRARIES="-L.. -lssl -L/usr/lib -lgssapi_krb5 -lkrb5 -lcom_err -lk5crypto -L.. -lcrypto" ; \
make -f ../Makefile.shared -e \
	APPNAME=openssl OBJECTS="openssl.o verify.o asn1pars.o req.o dgst.o dh.o dhparam.o enc.o passwd.o gendh.o errstr.o ca.o pkcs7.o crl2p7.o crl.o rsa.o rsautl.o dsa.o dsaparam.o ec.o ecparam.o x509.o genrsa.o gendsa.o genpkey.o s_server.o s_client.o speed.o s_time.o apps.o s_cb.o s_socket.o app_rand.o version.o sess_id.o ciphers.o nseq.o pkcs12.o pkcs8.o pkey.o pkeyparam.o pkeyutl.o spkac.o smime.o cms.o rand.o engine.o ocsp.o prime.o ts.o srp.o" \
	LIBDEPS=" $LIBRARIES -Wl,-z,relro -ldl -lz" \
	link_app.${shlib_target}
make[2]: Entering directory '/builddir/build/BUILD/openssl-1.0.1j/apps'
../libssl.so: undefined reference to `__secure_getenv'
collect2: error: ld returned 1 exit status
../Makefile.shared:171: recipe for target 'link_app.gnu' failed
make[2]: Leaving directory '/builddir/build/BUILD/openssl-1.0.1j/apps'
make[2]: *** [link_app.gnu] Error 1
make[1]: *** [openssl] Error 2
Makefile:153: recipe for target 'openssl' failed
make[1]: Leaving directory '/builddir/build/BUILD/openssl-1.0.1j/apps'
Makefile:289: recipe for target 'build_apps' failed

`

please advise.

**Comment by ptudor** [comment]
Fix the problem and send a request. I merge everything/anything.

**Comment by az-z** [comment]
i'm not sure what to fix.
I followed the directions and the thing won't compile.
if you can point to what i'm not doing right i'll glad to fish out the issue(s)

**Comment by az-z** [comment]
this can NOT be considered a bug - the package description is clearly states that it is for CENTOS 6.
There is quite a "gap" between F21 and Centos for obvious reasons. 
Closing as not a bug/issue.

**Comment by ptudor** [comment]
I didn't even read the subject. __secure_getenv is the first and simplest problem I addressed. It changed around... uh F18 or so. So that's why it's there. But if you're hacking on F21, just grab the most recent sprm, change the version numbers, try to build it, repeat as necessary. The guide and diff on my website is probably more useful as a framework for your purposes.

Copying from the guide I actually use, versus this repo I don't use or commit to that exists at the request of others (seriously anyone who needs FIPS has a Major Budget and hopefully isn't cloning arbitrary repos), just so you know the history of it:

cd /usr/src/redhat/SOURCES/
sed -i -e "s/secure_getenv/__secure_getenv/g" openssl-1.0.1e-env-zlib.patch
sed -i -e "s/secure_getenv/__secure_getenv/g" openssl-1.0.1e-fips-ctor.patch
sed -i -e "s/secure_getenv/__secure_getenv/g" openssl-1.0.1e-no-md5-verify.patch

**Comment by az-z** [comment]
@ptudor , indeed, the "getenv" was an easiest to solve actually. I'm trying to add curves to the package and it's quickly becoming a task on it's own. Late last night i came across openssl for bitcoin (http://www.ringingliberty.com/bitcoin/) and more specifically Michael's http://linux.ringingliberty.com/bitcoin/f21/SRPMS/repoview/openssl-compat-bitcoin.html srpm. But i felt asleep before mock finished.

**Comment by demofly** [comment]
http://sourceware.org/glibc/wiki/Tips_and_Tricks/secure_getenv
